## Default Connection Pool
## spring.datasource.url=jdbc:postgresql://localhost:5432/user-api
## spring.datasource.username=postgres
## spring.datasource.password=1234
## spring.jpa.hibernate.ddl-auto=update

server.port=8081

#spring.datasource.url=jdbc:h2:mem:testuserdb
spring.datasource.url=jdbc:h2:file:./data/dbuser
spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update